### ISSUE TITLE
README_first.ipynb needs updating

### ISSUE THREAD

**Issue by nmb-paperspace** [gradient-ai/Graphcore-Pytorch#19]
From Phase 2 to Phase 3

**Comment by nmb-paperspace** [comment]
Removing self-assign because Graphcore have updated the readme-firsts in the HF and TF repos.

**Comment by payoto** [comment]
Sorry @nmb-paperspace for the miscommunication, @JamesRandom was already working on it. 
Updated in #23 
I think we can close this issue with the latest commit

**Comment by nmb-paperspace** [comment]
Looks good! Closing as done.
