### ISSUE TITLE
efficient-data-loading.ipynb 4 IPUs remain attached

### ISSUE THREAD

**Issue by nmb-paperspace** [gradient-ai/Graphcore-Pytorch#25]
In `efficient-data-loading.ipynb`, `gc-monitor` said 4 IPUs were still attached after the notebook is finished running.

-> Detach same way as other notebooks.

**Comment by nmb-paperspace** [comment]
Stopping the notebook kernel detaches them, but the user may not do this

**Comment by rahult-graphcore** [comment]
There is a SW bug that is preventing the models from detaching when using synthetic data, so in the meantime we will add a cell to programmatically restart the kernel at the end of the notebook with an explanation to the user. This will be pushed in our next update to the gradient repo.

**Comment by nmb-paperspace** [comment]
OK that sounds good, thanks

**Comment by nmb-paperspace** [comment]
Confirmed working, although it triggers popup saying kernel died. Can close.
