### ISSUE TITLE
PyG-SchNetGNN.ipynb incomplete plot

### ISSUE THREAD

**Issue by nmb-paperspace** [gradient-ai/Graphcore-Pytorch#27]
The cell after “Plot the mean of the loss” fails with

```
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe'’
```

The output plot shows the main curve but not the ranges.

Might be related to NumPy 1.24; restarting the kernel and rerunning the notebook doesn’t clear it.

**Comment by rahult-graphcore** [comment]
This has been fixed in our internal repo, and will be updated on the gradient repo once the PR has been merged

**Comment by nmb-paperspace** [comment]
Plot looks OK now
