### ISSUE TITLE
vit-model-training notebook blocked: can't load data

### ISSUE THREAD

**Issue by nmb-paperspace** [gradient-ai/Graphcore-Pytorch#30]
In `vit-model-training/walkthrough.ipynb`, the cell `data = pd.read_csv(label_file)` fails with

```
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/dataset_cache/chest-xray-nihcc/Data_Entry_2017_v2020.csv'
```

The directory `/tmp/dataset_cache` is not present, and the `.csv` file is not elsewhere on the storage (I think). This blocks the rest of the notebook.

**Comment by rahult-graphcore** [comment]
The dataset is in the process of being uploaded to Paperspace, and the notebook has been removed from the runtime until then.

**Comment by payoto** [comment]
The notebook has been temporarily removed as this is worked on.

**Comment by nmb-paperspace** [comment]
New version https://github.com/gradient-ai/Graphcore-Pytorch/pull/44 doesn't have this error, so closing.
