### ISSUE TITLE
Setup instructions Slack channel link gives 404

### ISSUE THREAD

**Issue by nmb-paperspace** [gradient-ai/Graphcore-Pytorch#31]
"Running on Paperspace" cell links to https://nmy5fpurn6.clehbtvty.paperspacegradient.com/files/learning-PyTorch-on-IPU/basics/graphcorecommunity.slack.com?token=f84...6e2 (token abbreviated), which gives a Jupyter 404.

I assume this is the same on all notebooks since the instructions are merged as part of the repo setup.

**Comment by payoto** [comment]
Fixed by #36
